package My_Form;

import My_Class.Fun_Class;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

public class ManageGenresForm extends javax.swing.JFrame {

    My_Class.Genre genre = new My_Class.Genre();

    public ManageGenresForm() {
        initComponents();

        // center the form
        this.setLocationRelativeTo(null);

        // add a gray border to the panel
        Border panelHeaderBorder = BorderFactory.createMatteBorder(3, 3, 3, 3, Color.gray);
        jPanel1.setBorder(panelHeaderBorder);

        //Dispaly image in the top
        My_Class.Fun_Class func = new Fun_Class();
        // this display image  in the dashbord left side
        // func.displayImage(jLabel_Form_Title.getWidth(), jLabel_Form_Title.getHeight(), "/My_image/", jLabel_Form_Title);
        func.displayImage(76, 50,null, "/My_image/book_02.png", jLabel_Form_Title);

        // custom the jtable
//        jTable_genres_.setSelectionBackground(new Color(249, 105, 14));
//        jTable_genres_.setRowHeight(30);
//        jTable_genres_.setSelectionForeground(Color.white);
//        //        jTable_genres_.setShowGrid(true);
//        jTable_genres_.setBackground(new Color(248, 248, 247));
// short hand code cell fun_Class to custom the jtable
func.customTable(jTable_genres_);

        //Customize the jtable header row
        jTable_genres_.getTableHeader().setBackground(Color.red);
        jTable_genres_.getTableHeader().setForeground(Color.white);
        jTable_genres_.getTableHeader().setFont(new Font("Verdana", Font.BOLD, 20));
        jTable_genres_.getTableHeader().setOpaque(false);

        // hide the jLable "empty name massage
        jLabel_Empty_Name_.setVisible(false);

        // populateJTableGeres 
        populateJTableGeres();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_Form_Title = new javax.swing.JLabel();
        jLabel_close_ = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_ID_ = new javax.swing.JTextField();
        jTextField_Name_ = new javax.swing.JTextField();
        jButton_Delete_ = new javax.swing.JButton();
        jButton_add_ = new javax.swing.JButton();
        jButton_Edit_ = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_genres_ = new javax.swing.JTable();
        jLabel_Empty_Name_ = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_Form_Title.setBackground(java.awt.Color.gray);
        jLabel_Form_Title.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel_Form_Title.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Form_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Form_Title.setText("Manage Books Genres");
        jLabel_Form_Title.setOpaque(true);

        jLabel_close_.setBackground(java.awt.Color.gray);
        jLabel_close_.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel_close_.setForeground(java.awt.Color.gray);
        jLabel_close_.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_close_.setText("X");
        jLabel_close_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_close_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_close_MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel1.setText("ID :");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel2.setText("Name :");

        jTextField_ID_.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jTextField_Name_.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jButton_Delete_.setFont(new java.awt.Font("Segoe UI Historic", 0, 24)); // NOI18N
        jButton_Delete_.setText("Delete");
        jButton_Delete_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Delete_ActionPerformed(evt);
            }
        });

        jButton_add_.setFont(new java.awt.Font("Segoe UI Historic", 0, 24)); // NOI18N
        jButton_add_.setText("Add");
        jButton_add_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_add_ActionPerformed(evt);
            }
        });

        jButton_Edit_.setFont(new java.awt.Font("Segoe UI Historic", 0, 24)); // NOI18N
        jButton_Edit_.setText("Edit");
        jButton_Edit_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Edit_ActionPerformed(evt);
            }
        });

        jTable_genres_.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable_genres_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_genres_MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_genres_);

        jLabel_Empty_Name_.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_Empty_Name_.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel_Empty_Name_.setForeground(new java.awt.Color(153, 0, 0));
        jLabel_Empty_Name_.setText("* Enter the Genre");
        jLabel_Empty_Name_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Empty_Name_MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel_Form_Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_close_, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jButton_add_, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_Delete_, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_Edit_, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_ID_)
                            .addComponent(jTextField_Name_)
                            .addComponent(jLabel_Empty_Name_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Form_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_close_, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField_ID_, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                            .addComponent(jTextField_Name_))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_Empty_Name_, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jButton_Edit_)
                            .addComponent(jButton_Delete_)
                            .addComponent(jButton_add_))
                        .addGap(51, 51, 51))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(48, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 844, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //closse the panale

    private void jLabel_close_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_close_MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel_close_MouseClicked

    private void jButton_add_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_add_ActionPerformed
        // add a new gener
        String name = jTextField_Name_.getText();

        // check if the textField is empty
        if (name.isEmpty()) {
//            System.out.println("empty");
            jLabel_Empty_Name_.setVisible(true);

        } else {
            // System.out.println("no");
            //  My_Class.Genre genre = new Genre();
            genre.addGenre(name);

            //refreseh the  populateJTableGeres
            populateJTableGeres();

        }
    }//GEN-LAST:event_jButton_add_ActionPerformed

    private void jButton_Edit_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Edit_ActionPerformed
        // TODO add your handling code here:
        //edit the selectde genre
        // int id = Integer.valueOf(jTextField_ID_.getText()); this variable used in else statement 
        String name = jTextField_Name_.getText();
        if (name.isEmpty()) {
//            System.out.println("empty"); 
            jLabel_Empty_Name_.setVisible(true);

        } else {
            try {
                int id = Integer.parseInt(jTextField_ID_.getText());
                genre.editGenre(id, name);

                //refreseh the  populateJTableGeres
                populateJTableGeres();
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Invalid Book  Id", "Error", 3);
            }
        }
    }//GEN-LAST:event_jButton_Edit_ActionPerformed

    private void jButton_Delete_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Delete_ActionPerformed

        // delete htee selection text
        try {
            int id = Integer.parseInt(jTextField_ID_.getText());
            genre.removeGenre(id);
               //refreseh the  populateJTableGeres
             populateJTableGeres();
             
             // clear text from the textField
             jTextField_ID_.setText("");
             jTextField_Name_.setText("");
             
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Invalid Book  Id" + ex.getMessage(), "Error", 0);
        }
    }//GEN-LAST:event_jButton_Delete_ActionPerformed

    private void jTable_genres_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_genres_MouseClicked
        // display the selscted gener

        // get the selection row index
        int index = jTable_genres_.getSelectedRow();

        //get value
        String id = jTable_genres_.getValueAt(index, 0).toString();
        String name = jTable_genres_.getValueAt(index, 1).toString();

        // show data in textfield
        jTextField_ID_.setText(id);
        jTextField_Name_.setText(name);


    }//GEN-LAST:event_jTable_genres_MouseClicked

    // create a unction to poplate the jtable with book
    public void populateJTableGeres() {

        ArrayList<My_Class.Genre> genresList = genre.genreList();
        // jTable
        String[] colName = {"id", "Name"};

        // row
        Object[][] row = new Object[genresList.size()][colName.length];
        for (int i = 0; i < genresList.size(); i++) {
            row[i][0] = genresList.get(i).getId();
            row[i][1] = genresList.get(i).getName();

        }
        DefaultTableModel model = new DefaultTableModel(row, colName);
        jTable_genres_.setModel(model);

    }

    private void jLabel_Empty_Name_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Empty_Name_MouseClicked

        // hide this jlable on click
        jLabel_Empty_Name_.setVisible(false);
    }//GEN-LAST:event_jLabel_Empty_Name_MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    //javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageGenresForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageGenresForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageGenresForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageGenresForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageGenresForm().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Delete_;
    private javax.swing.JButton jButton_Edit_;
    private javax.swing.JButton jButton_add_;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_Empty_Name_;
    private javax.swing.JLabel jLabel_Form_Title;
    private javax.swing.JLabel jLabel_close_;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_genres_;
    private javax.swing.JTextField jTextField_ID_;
    private javax.swing.JTextField jTextField_Name_;
    // End of variables declaration//GEN-END:variables
}
