package My_Form;

import My_Class.Member;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

public class MemberListForm extends javax.swing.JFrame {

    My_Class.Member member = new My_Class.Member();
    My_Class.Fun_Class func = new My_Class.Fun_Class();

    public MemberListForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        // add a gray border to the panel
        Border panelHeaderBorder = BorderFactory.createMatteBorder(3, 3, 3, 3, new Color(1, 50, 74));
        jPanel11.setBorder(panelHeaderBorder);

        // display Image in the top
        func.displayImage(80, 80, null, "/My_image/4185556.png", jLabel_Form_Title);

        // custom the jtable
        func.customTable(jTable_Member_List_);

        //short hand 
        func.customTableHeader(jTable_Member_List_, new Color(42, 108, 150), 16);

        // display member in the jtable
        populateJTableMember("");// dont use space in the cotation
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel11 = new javax.swing.JPanel();
        Titlebar = new javax.swing.JPanel();
        jLabel_Form_Title = new javax.swing.JLabel();
        jLabel_Form_Title1 = new javax.swing.JLabel();
        form = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_Search_ = new javax.swing.JTextField();
        jLabel_Empty_ID_ = new javax.swing.JLabel();
        jButton_Search_ = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Member_List_ = new javax.swing.JTable();
        jLabel_image_view = new javax.swing.JLabel();
        jLabel_full_Name_ = new javax.swing.JLabel();
        jLabel_Phone_ = new javax.swing.JLabel();
        jLabel_Email_ = new javax.swing.JLabel();
        jLabel_Gender_ = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setPreferredSize(new java.awt.Dimension(460, 300));

        Titlebar.setBackground(new java.awt.Color(255, 255, 255));
        Titlebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Form_Title.setBackground(new java.awt.Color(11, 150, 117));
        jLabel_Form_Title.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel_Form_Title.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Form_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Form_Title.setText("Members List");
        jLabel_Form_Title.setOpaque(true);
        Titlebar.add(jLabel_Form_Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 66));

        jLabel_Form_Title1.setBackground(new java.awt.Color(11, 150, 117));
        jLabel_Form_Title1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel_Form_Title1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Form_Title1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Form_Title1.setText("x");
        jLabel_Form_Title1.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel_Form_Title1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Form_Title1.setOpaque(true);
        jLabel_Form_Title1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Form_Title1MouseClicked(evt);
            }
        });
        Titlebar.add(jLabel_Form_Title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, -10, 90, 80));

        form.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        jLabel2.setText("Value to search:");

        jTextField_Search_.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jLabel_Empty_ID_.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_Empty_ID_.setForeground(new java.awt.Color(153, 0, 0));
        jLabel_Empty_ID_.setText("You must enter the member ID(id desite)");
        jLabel_Empty_ID_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Empty_ID_MouseClicked(evt);
            }
        });

        jButton_Search_.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton_Search_.setText("Search");
        jButton_Search_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Search_ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formLayout = new javax.swing.GroupLayout(form);
        form.setLayout(formLayout);
        formLayout.setHorizontalGroup(
            formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_Search_, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Search_, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
            .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(formLayout.createSequentialGroup()
                    .addGap(161, 161, 161)
                    .addComponent(jLabel_Empty_ID_, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(287, Short.MAX_VALUE)))
        );
        formLayout.setVerticalGroup(
            formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_Search_, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(formLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_Search_, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(78, 78, 78))
            .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(formLayout.createSequentialGroup()
                    .addGap(45, 45, 45)
                    .addComponent(jLabel_Empty_ID_, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(46, Short.MAX_VALUE)))
        );

        jTable_Member_List_.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable_Member_List_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_Member_List_MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Member_List_);

        jLabel_image_view.setBackground(new java.awt.Color(102, 204, 255));

        jLabel_full_Name_.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel_full_Name_.setText("Full Name :");

        jLabel_Phone_.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel_Phone_.setText("Phone :");

        jLabel_Email_.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel_Email_.setText("Email :");

        jLabel_Gender_.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel_Gender_.setText("Gender :");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(Titlebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(form, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(28, 28, 28)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_full_Name_, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Phone_, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Email_, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Gender_, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_image_view, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(102, 102, 102))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addComponent(Titlebar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(form, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel_image_view, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_full_Name_, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_Phone_, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_Email_, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_Gender_, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 966, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_Form_Title1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Form_Title1MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel_Form_Title1MouseClicked

    private void jButton_Search_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Search_ActionPerformed
        // search and bisplay data in the jtable
        String value = jTextField_Search_.getText();
        String qurey = "SELECT * FROM `member` WHERE `firstName`LIKE'%" + value + "%' OR `lastName` LIKE '%" + value + "%' ";
        populateJTableMember(qurey);
    }//GEN-LAST:event_jButton_Search_ActionPerformed

    private void jLabel_Empty_ID_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Empty_ID_MouseClicked

        // hide this jlable on click
    }//GEN-LAST:event_jLabel_Empty_ID_MouseClicked

    private void jTable_Member_List_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_Member_List_MouseClicked
        // Display the selected Member Data
        try {
            // seatch member by ID
            Integer rowIndex = jTable_Member_List_.getSelectedRow();// get the selected jTable row index

            // get the member id from the jTAble (the id is the first column [0])
            Integer id = Integer.parseInt(jTable_Member_List_.getModel().getValueAt(rowIndex, 0).toString());
            //get data
            Member SelectdMember = member.getMemberById(id);

            if (SelectdMember != null) {
                jLabel_full_Name_.setText(SelectdMember.getFirstName() + " " + SelectdMember.getLastName());
                jLabel_Phone_.setText(SelectdMember.getPhone());
                jLabel_Email_.setText(SelectdMember.getEmail());
                jLabel_Gender_.setText(SelectdMember.getGender());

                // display the member image
                byte[] image = SelectdMember.getPicture();

                func.displayImage(90, 60, image, "", jLabel_image_view);
            } else {
                JOptionPane.showMessageDialog(null, "NO member with theis id Found", "Invalit ID", 3);
            }

        } catch (SQLException | NumberFormatException ex) {
            // Logger.getLogger(EditMember.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Enter a valid Member ID", "Invalit ID", 3);
        }
    }//GEN-LAST:event_jTable_Member_List_MouseClicked

    // create a function to poplate the jtable with Member
    public void populateJTableMember(String query) {
        ArrayList<My_Class.Member> memberList = member.memberList(query);
        // jTable
        String[] colName = {"id", "F-Name", "L-Name", "phone", "email", "Gender"};

        // row
        Object[][] row = new Object[memberList.size()][colName.length];
        for (int i = 0; i < memberList.size(); i++) {
            row[i][0] = memberList.get(i).getId();
            row[i][1] = memberList.get(i).getFirstName();
            row[i][2] = memberList.get(i).getLastName();
            row[i][3] = memberList.get(i).getPhone();
            row[i][4] = memberList.get(i).getEmail();
            row[i][5] = memberList.get(i).getGender();
//            row[i][4] = memberList.get(i).getPicture();

        }
        DefaultTableModel model = new DefaultTableModel(row, colName);
        jTable_Member_List_.setModel(model);

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MemberListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MemberListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MemberListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MemberListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MemberListForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Titlebar;
    private javax.swing.JPanel form;
    private javax.swing.JButton jButton_Search_;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_Email_;
    private javax.swing.JLabel jLabel_Empty_ID_;
    private javax.swing.JLabel jLabel_Form_Title;
    private javax.swing.JLabel jLabel_Form_Title1;
    private javax.swing.JLabel jLabel_Gender_;
    private javax.swing.JLabel jLabel_Phone_;
    private javax.swing.JLabel jLabel_full_Name_;
    private javax.swing.JLabel jLabel_image_view;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Member_List_;
    private javax.swing.JTextField jTextField_Search_;
    // End of variables declaration//GEN-END:variables
}
